
name: 'Push directory to another repository'

description: 'Useful to push files to another repository to be used, for example, via github pages'

inputs:
    package-directory:
        description: 'Local package directory'
        required: true
    destination-github-username:
        description: 'Remote organization'
        required: true
    destination-repository-name:
        description: 'Remove repository'
        required: true
    user-email:
        description: 'Email for the git commit'
        required: true

    commit-message:
        description: '[Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo'
        default: 'Package split ORIGIN_COMMIT'
        required: false

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.package-directory }}
        - ${{ inputs.destination-github-username }}
        - ${{ inputs.destination-repository-name }}
        - ${{ inputs.user-email }}
        - ${{ inputs.commit-message }}
