name: code-analysis

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        actions:
          - name: 'PHPStan'
            run: composer phpstan
          - name: 'Coding Standard'
            run: composer check-cs

    name: ${{ matrix.actions.name }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: 8.1
          coverage: none

      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - run: ${{ matrix.actions.run }}
