# see .github/workflows/build-docker-images.yml
name: pull-docker-image

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@371161bbe7024a29a25c5e19bfcbc0804fe9ad2c # v4.5.2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/monorepo-split:latest
