name: split-test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  split-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      # run action.yaml in the root directory
      # see https://github.community/t/self-reference-an-action-for-testing/17891
      - uses: "./"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'tests/packages/some-package'
          repository_organization: 'symplify'
          repository_name: 'monorepo-split-github-action-test'

          user_name: 'kaizen-ci'
          user_email: 'info@kaizen-ci.org'
